# Generated by Django 4.1.8 on 2023-05-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_project_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_details',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='priority',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='project',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project_details',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
