# Generated by Django 4.1.8 on 2023-05-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='idx',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
