# Generated by Django 4.1.8 on 2023-05-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_todo_idx_alter_todo_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo',
            new_name='todo1',
        ),
    ]
